// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	types "github.com/SmartBFT-Go/consensus/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// AssemblerMock is an autogenerated mock type for the AssemblerMock type
type AssemblerMock struct {
	mock.Mock
}

// AssembleProposal provides a mock function with given fields: metadata, requests
func (_m *AssemblerMock) AssembleProposal(metadata []byte, requests [][]byte) types.Proposal {
	ret := _m.Called(metadata, requests)

	var r0 types.Proposal
	if rf, ok := ret.Get(0).(func([]byte, [][]byte) types.Proposal); ok {
		r0 = rf(metadata, requests)
	} else {
		r0 = ret.Get(0).(types.Proposal)
	}

	return r0
}

type mockConstructorTestingTNewAssemblerMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewAssemblerMock creates a new instance of AssemblerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAssemblerMock(t mockConstructorTestingTNewAssemblerMock) *AssemblerMock {
	mock := &AssemblerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
