// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	types "github.com/SmartBFT-Go/consensus/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// Decider is an autogenerated mock type for the Decider type
type Decider struct {
	mock.Mock
}

// Decide provides a mock function with given fields: proposal, signatures, requests
func (_m *Decider) Decide(proposal types.Proposal, signatures []types.Signature, requests []types.RequestInfo) {
	_m.Called(proposal, signatures, requests)
}

type mockConstructorTestingTNewDecider interface {
	mock.TestingT
	Cleanup(func())
}

// NewDecider creates a new instance of Decider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDecider(t mockConstructorTestingTNewDecider) *Decider {
	mock := &Decider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
