// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MembershipNotifierMock is an autogenerated mock type for the MembershipNotifierMock type
type MembershipNotifierMock struct {
	mock.Mock
}

// MembershipChange provides a mock function with given fields:
func (_m *MembershipNotifierMock) MembershipChange() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewMembershipNotifierMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewMembershipNotifierMock creates a new instance of MembershipNotifierMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMembershipNotifierMock(t mockConstructorTestingTNewMembershipNotifierMock) *MembershipNotifierMock {
	mock := &MembershipNotifierMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
