// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Pruner is an autogenerated mock type for the Pruner type
type Pruner struct {
	mock.Mock
}

// MaybePruneRevokedRequests provides a mock function with given fields:
func (_m *Pruner) MaybePruneRevokedRequests() {
	_m.Called()
}

type mockConstructorTestingTNewPruner interface {
	mock.TestingT
	Cleanup(func())
}

// NewPruner creates a new instance of Pruner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPruner(t mockConstructorTestingTNewPruner) *Pruner {
	mock := &Pruner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
