// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	types "github.com/SmartBFT-Go/consensus/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// RequestsTimer is an autogenerated mock type for the RequestsTimer type
type RequestsTimer struct {
	mock.Mock
}

// RemoveRequest provides a mock function with given fields: request
func (_m *RequestsTimer) RemoveRequest(request types.RequestInfo) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.RequestInfo) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestartTimers provides a mock function with given fields:
func (_m *RequestsTimer) RestartTimers() {
	_m.Called()
}

// StopTimers provides a mock function with given fields:
func (_m *RequestsTimer) StopTimers() {
	_m.Called()
}

type mockConstructorTestingTNewRequestsTimer interface {
	mock.TestingT
	Cleanup(func())
}

// NewRequestsTimer creates a new instance of RequestsTimer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRequestsTimer(t mockConstructorTestingTNewRequestsTimer) *RequestsTimer {
	mock := &RequestsTimer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
